spring:
  application:
    name: notifications-ms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-ms-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
